export const example1 = { BigIntSupported: 1111, date: '20180322', message: 'Success !', status: 200, city: '北京', count: 632, data: { shidu: '34%', pm25: 73, pm10: 91, quality: '良', wendu: '5', ganmao: '极少数敏感人群应减少户外活动', yesterday: { date: '21日星期三', sunrise: '06:19', high: '高温 11.0℃', low: '低温 1.0℃', sunset: '18:26', aqi: 85, fx: '南风', fl: '<3级', type: '多云', notice: '阴晴之间，谨防紫外线侵扰' }, forecast: [{ date: '22日星期四', sunrise: '06:17', high: '高温 17.0℃', low: '低温 1.0℃', sunset: '18:27', aqi: 98, fx: '西南风', fl: '<3级', type: '晴', notice: '愿你拥有比阳光明媚的心情' }, { date: '23日星期五', sunrise: '06:16', high: '高温 18.0℃', low: '低温 5.0℃', sunset: '18:28', aqi: 118, fx: '无持续风向', fl: '<3级', type: '多云', notice: '阴晴之间，谨防紫外线侵扰' }, { date: '24日星期六', sunrise: '06:14', high: '高温 21.0℃', low: '低温 7.0℃', sunset: '18:29', aqi: 52, fx: '西南风', fl: '<3级', type: '晴', notice: '愿你拥有比阳光明媚的心情' }, { date: '25日星期日', sunrise: '06:13', high: '高温 22.0℃', low: '低温 7.0℃', sunset: '18:30', aqi: 71, fx: '西南风', fl: '<3级', type: '晴', notice: '愿你拥有比阳光明媚的心情' }, { date: '26日星期一', sunrise: '06:11', high: '高温 21.0℃', low: '低温 8.0℃', sunset: '18:31', aqi: 97, fx: '西南风', fl: '<3级', type: '多云', notice: '阴晴之间，谨防紫外线侵扰' }] } }

export const example2 = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg',
      id: 94997,
      name: 'House of the Dragon',
      original_language: 'en',
      original_name: 'House of the Dragon',
      overview: 'The Targaryen dynasty is at the absolute apex of its power, with more than 15 dragons under their yoke. Most empires crumble from such heights. In the case of the Targaryens, their slow fall begins when King Viserys breaks with a century of tradition by naming his daughter Rhaenyra heir to the Iron Throne. But when Viserys later fathers a son, the court is shocked when Rhaenyra retains her status as his heir, and seeds of division sow friction across the realm.',
      poster_path: '/z2yahl2uefxDCl0nogcRBstwruJ.jpg',
      media_type: 'tv',
      genre_ids: [
        10765,
        18,
        10759,
      ],
      popularity: 5118.792,
      first_air_date: '2022-08-21',
      vote_average: 8.533,
      vote_count: 2097,
      origin_country: [
        'US',
      ],
    },
    {
      adult: false,
      backdrop_path: '/d6MhreFdMHONqX3iZlJGCF8UkIt.jpg',
      id: 436270,
      title: 'Black Adam',
      original_language: 'en',
      original_title: 'Black Adam',
      overview: 'Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods—and imprisoned just as quickly—Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.',
      poster_path: '/3zXceNTtyj5FLjwQXuPvLYK5YYL.jpg',
      media_type: 'movie',
      genre_ids: [
        28,
        12,
        14,
      ],
      popularity: 4416.78,
      release_date: '2022-10-19',
      video: false,
      vote_average: 7.123,
      vote_count: 518,
    },
    {
      adult: false,
      backdrop_path: '/aTovumsNlDjof7YVoU5nW2RHaYn.jpg',
      id: 616820,
      title: 'Halloween Ends',
      original_language: 'en',
      original_title: 'Halloween Ends',
      overview: 'Four years after the events of Halloween in 2018, Laurie has decided to liberate herself from fear and rage and embrace life. But when a young man is accused of killing a boy he was babysitting, it ignites a cascade of violence and terror that will force Laurie to finally confront the evil she can’t control, once and for all.',
      poster_path: '/kFMntvUmKhvw1uAHXecqqNSFXt.jpg',
      media_type: 'movie',
      genre_ids: [
        27,
        53,
      ],
      popularity: 2313.949,
      release_date: '2022-10-12',
      video: false,
      vote_average: 6.688,
      vote_count: 695,
    },
    {
      adult: false,
      backdrop_path: '/1rO4xoCo4Z5WubK0OwdVll3DPYo.jpg',
      id: 84773,
      name: 'The Lord of the Rings: The Rings of Power',
      original_language: 'en',
      original_name: 'The Lord of the Rings: The Rings of Power',
      overview: 'Beginning in a time of relative peace, we follow an ensemble cast of characters as they confront the re-emergence of evil to Middle-earth. From the darkest depths of the Misty Mountains, to the majestic forests of Lindon, to the breathtaking island kingdom of Númenor, to the furthest reaches of the map, these kingdoms and characters will carve out legacies that live on long after they are gone.',
      poster_path: '/mYLOqiStMxDK3fYZFirgrMt8z5d.jpg',
      media_type: 'tv',
      genre_ids: [
        10765,
        10759,
        18,
      ],
      popularity: 3133.189,
      first_air_date: '2022-09-01',
      vote_average: 7.659,
      vote_count: 1328,
      origin_country: [
        'US',
      ],
    },
    {
      adult: false,
      backdrop_path: '/tSxbUnrnWlR5dQvUgqMI7sACmFD.jpg',
      id: 779782,
      title: 'The School for Good and Evil',
      original_language: 'en',
      original_title: 'The School for Good and Evil',
      overview: 'Best friends Sophie and Agatha navigate an enchanted school for young heroes and villains — and find themselves on opposing sides of the battle between good and evil.',
      poster_path: '/6oZeEu1GDILdwezmZ5e2xWISf1C.jpg',
      media_type: 'movie',
      genre_ids: [
        14,
        28,
        18,
      ],
      popularity: 973.914,
      release_date: '2022-10-19',
      video: false,
      vote_average: 7.384,
      vote_count: 333,
    },
    {
      adult: false,
      backdrop_path: '/zt6sKnx9dEiRCb7oVMlfmmMGJMO.jpg',
      id: 718930,
      title: 'Bullet Train',
      original_language: 'en',
      original_title: 'Bullet Train',
      overview: "Unlucky assassin Ladybug is determined to do his job peacefully after one too many gigs gone off the rails. Fate, however, may have other plans, as Ladybug's latest mission puts him on a collision course with lethal adversaries from around the globe—all with connected, yet conflicting, objectives—on the world's fastest train.",
      poster_path: '/tVxDe01Zy3kZqaZRNiXFGDICdZk.jpg',
      media_type: 'movie',
      genre_ids: [
        28,
        35,
        53,
      ],
      popularity: 1812.839,
      release_date: '2022-07-03',
      video: false,
      vote_average: 7.519,
      vote_count: 2010,
    },
    {
      adult: false,
      backdrop_path: '/4O9kFXsBjlxtgzXWHfgMS9CjhbN.jpg',
      id: 619730,
      title: "Don't Worry Darling",
      original_language: 'en',
      original_title: "Don't Worry Darling",
      overview: 'Alice and Jack are lucky to be living in the idealized community of Victory, the experimental company town housing the men who work for the top-secret Victory Project and their families. But when cracks in their idyllic life begin to appear, exposing flashes of something much more sinister lurking beneath the attractive façade, Alice can’t help questioning exactly what they’re doing in Victory, and why.',
      poster_path: '/9BXYLjXtSipBp2GfAlsri4i8hPC.jpg',
      media_type: 'movie',
      genre_ids: [
        53,
        9648,
        18,
      ],
      popularity: 502.412,
      release_date: '2022-09-21',
      video: false,
      vote_average: 6.867,
      vote_count: 550,
    },
    {
      adult: false,
      backdrop_path: '/bUjPcNS8GweBh5Nxp8oq9Dy712Z.jpg',
      id: 913290,
      title: 'Barbarian',
      original_language: 'en',
      original_title: 'Barbarian',
      overview: 'In town for a job interview, a young woman arrives at her Airbnb late at night only to find that it has been mistakenly double-booked and a strange man is already staying there. Against her better judgement, she decides to stay the night anyway, but soon discovers that there is much more to be afraid of in the house than the other guest.',
      poster_path: '/idT5mnqPcJgSkvpDX7pJffBzdVH.jpg',
      media_type: 'movie',
      genre_ids: [
        27,
        9648,
        53,
      ],
      popularity: 269.235,
      release_date: '2022-09-08',
      video: false,
      vote_average: 7.148,
      vote_count: 152,
    },
    {
      adult: false,
      backdrop_path: '/hIZFG7MK4leU4axRFKJWqrjhmxZ.jpg',
      id: 95403,
      name: 'The Peripheral',
      original_language: 'en',
      original_name: 'The Peripheral',
      overview: 'Stuck in a small Appalachian town, a young woman’s only escape from the daily grind is playing advanced video games. She is such a good player that a company sends her a new video game system to test…but it has a surprise in store. It unlocks all of her dreams of finding a purpose, romance, and glamour in what seems like a game…but it also puts her and her family in real danger.',
      poster_path: '/qtuAjmUWY7xIEOg0yfpqLkHSeeu.jpg',
      media_type: 'tv',
      genre_ids: [
        10765,
        18,
      ],
      popularity: 399.51,
      first_air_date: '2022-10-20',
      vote_average: 8.389,
      vote_count: 95,
      origin_country: [
        'US',
      ],
    },
    {
      adult: false,
      backdrop_path: '/ajztm40qDPqMONaSJhQ2PaNe2Xd.jpg',
      id: 83867,
      name: 'Star Wars: Andor',
      original_language: 'en',
      original_name: 'Star Wars: Andor',
      overview: 'The tale of the burgeoning rebellion against the Empire and how people and planets became involved. In an era filled with danger, deception and intrigue, Cassian Andor embarks on the path that is destined to turn him into a rebel hero.',
      poster_path: '/59SVNwLfoMnZPPB6ukW6dlPxAdI.jpg',
      media_type: 'tv',
      genre_ids: [
        10765,
        10759,
        10768,
      ],
      popularity: 932.493,
      first_air_date: '2022-09-21',
      vote_average: 8.03,
      vote_count: 184,
      origin_country: [
        'US',
      ],
    },
    {
      adult: false,
      backdrop_path: '/qtfMr08KQsWXnCHY0a96N8NpQ2l.jpg',
      id: 30984,
      name: 'Bleach',
      original_language: 'ja',
      original_name: 'ブリーチ',
      overview: 'For as long as he can remember, Ichigo Kurosaki has been able to see ghosts. But when he meets Rukia, a Soul Reaper who battles evil spirits known as Hollows, he finds his life is changed forever. Now, with a newfound wealth of spiritual energy, Ichigo discovers his true calling: to protect the living and the dead from evil.',
      poster_path: '/2EewmxXe72ogD0EaWM8gqa0ccIw.jpg',
      media_type: 'tv',
      genre_ids: [
        10759,
        16,
        10765,
      ],
      popularity: 267.214,
      first_air_date: '2004-10-05',
      vote_average: 8.361,
      vote_count: 1306,
      origin_country: [
        'JP',
      ],
    },
    {
      adult: false,
      backdrop_path: '/9GvhICFMiRQA82vS6ydkXxeEkrd.jpg',
      id: 92783,
      name: 'She-Hulk: Attorney at Law',
      original_language: 'en',
      original_name: 'She-Hulk: Attorney at Law',
      overview: 'Jennifer Walters navigates the complicated life of a single, 30-something attorney who also happens to be a green 6-foot-7-inch superpowered hulk.',
      poster_path: '/hJfI6AGrmr4uSHRccfJuSsapvOb.jpg',
      media_type: 'tv',
      genre_ids: [
        35,
        10765,
      ],
      popularity: 1350.101,
      first_air_date: '2022-08-18',
      vote_average: 6.777,
      vote_count: 1172,
      origin_country: [
        'US',
      ],
    },
    {
      adult: false,
      backdrop_path: '/odJ4hx6g6vBt4lBWKFD1tI8WS4x.jpg',
      id: 361743,
      title: 'Top Gun: Maverick',
      original_language: 'en',
      original_title: 'Top Gun: Maverick',
      overview: 'After more than thirty years of service as one of the Navy’s top aviators, and dodging the advancement in rank that would ground him, Pete “Maverick” Mitchell finds himself training a detachment of TOP GUN graduates for a specialized mission the likes of which no living pilot has ever seen.',
      poster_path: '/62HCnUTziyWcpDaBO2i1DX17ljH.jpg',
      media_type: 'movie',
      genre_ids: [
        28,
        18,
      ],
      popularity: 897.984,
      release_date: '2022-05-24',
      video: false,
      vote_average: 8.35,
      vote_count: 4438,
    },
    {
      adult: false,
      backdrop_path: '/pfAZP7JvTTxqgq7n6A1OYgkAdEW.jpg',
      id: 894205,
      title: 'Werewolf by Night',
      original_language: 'en',
      original_title: 'Werewolf by Night',
      overview: 'On a dark and somber night, a secret cabal of monster hunters emerge from the shadows and gather at the foreboding Bloodstone Temple following the death of their leader. In a strange and macabre memorial to the leader’s life, the attendees are thrust into a mysterious and deadly competition for a powerful relic—a hunt that will ultimately bring them face to face with a dangerous monster.',
      poster_path: '/jmv7EbqBuEk4V1U7OoSBaxkwawO.jpg',
      media_type: 'movie',
      genre_ids: [
        28,
        14,
        27,
        10770,
      ],
      popularity: 504.312,
      release_date: '2022-09-25',
      video: false,
      vote_average: 7.213,
      vote_count: 520,
    },
    {
      adult: false,
      backdrop_path: '/ulyR4pWVMRtVcanoassVbmgfEPT.jpg',
      id: 800939,
      title: 'Ticket to Paradise',
      original_language: 'en',
      original_title: 'Ticket to Paradise',
      overview: 'A divorced couple teams up and travels to Bali to stop their daughter from making the same mistake they think they made 25 years ago.',
      poster_path: '/1tzERH50P5c2mFWtLbgixzLZS1L.jpg',
      media_type: 'movie',
      genre_ids: [
        35,
        10749,
      ],
      popularity: 232.797,
      release_date: '2022-09-08',
      video: false,
      vote_average: 6.745,
      vote_count: 141,
    },
    {
      adult: false,
      backdrop_path: '/rpTpgiwj63N2f6HnB5SKhei5N80.jpg',
      id: 83659,
      name: "Guillermo del Toro's Cabinet of Curiosities",
      original_language: 'en',
      original_name: "Guillermo del Toro's Cabinet of Curiosities",
      overview: 'Bizarre nightmares unfold in eight tales of terror in this visually stunning, spine-tingling horror collection curated by Guillermo del Toro.',
      poster_path: '/a91e9hpWwfCqxJI4xM9Q2RhuxgI.jpg',
      media_type: 'tv',
      genre_ids: [
        18,
        9648,
      ],
      popularity: 130.341,
      first_air_date: '2022-10-25',
      vote_average: 7.7,
      vote_count: 28,
      origin_country: [
        'US',
      ],
    },
    {
      adult: false,
      backdrop_path: '/jsoz1HlxczSuTx0mDl2h0lxy36l.jpg',
      id: 616037,
      title: 'Thor: Love and Thunder',
      original_language: 'en',
      original_title: 'Thor: Love and Thunder',
      overview: 'After his retirement is interrupted by Gorr the God Butcher, a galactic killer who seeks the extinction of the gods, Thor Odinson enlists the help of King Valkyrie, Korg, and ex-girlfriend Jane Foster, who now wields Mjolnir as the Mighty Thor. Together they embark upon a harrowing cosmic adventure to uncover the mystery of the God Butcher’s vengeance and stop him before it’s too late.',
      poster_path: '/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg',
      media_type: 'movie',
      genre_ids: [
        14,
        28,
        35,
      ],
      popularity: 1130.422,
      release_date: '2022-07-06',
      video: false,
      vote_average: 6.734,
      vote_count: 4395,
    },
    {
      adult: false,
      backdrop_path: '/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg',
      id: 634649,
      title: 'Spider-Man: No Way Home',
      original_language: 'en',
      original_title: 'Spider-Man: No Way Home',
      overview: 'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.',
      poster_path: '/uJYYizSuA9Y3DCs0qS4qWvHfZg4.jpg',
      media_type: 'movie',
      genre_ids: [
        28,
        12,
        878,
      ],
      popularity: 804.571,
      release_date: '2021-12-15',
      video: false,
      vote_average: 8.031,
      vote_count: 15607,
    },
    {
      adult: false,
      backdrop_path: '/7UQVtlZl7Hh6Zae8r0RopHQ8y2y.jpg',
      id: 949423,
      title: 'Pearl',
      original_language: 'en',
      original_title: 'Pearl',
      overview: 'Trapped on her family’s isolated farm, Pearl must tend to her ailing father under the bitter and overbearing watch of her devout mother. Lusting for a glamorous life like she’s seen in the movies, Pearl’s ambitions, temptations and repressions collide.',
      poster_path: '/ulBLIBqvdnf4H6JBt0OpMCU1ECn.jpg',
      media_type: 'movie',
      genre_ids: [
        27,
        53,
        18,
      ],
      popularity: 183.714,
      release_date: '2022-09-16',
      video: false,
      vote_average: 7.1,
      vote_count: 86,
    },
    {
      adult: false,
      backdrop_path: '/sRfl6vyzGWutgG0cmXmbChC4iN6.jpg',
      id: 57243,
      name: 'Doctor Who',
      original_language: 'en',
      original_name: 'Doctor Who',
      overview: "The Doctor is a Time Lord: a 900 year old alien with 2 hearts, part of a gifted civilization who mastered time travel. The Doctor saves planets for a living—more of a hobby actually, and the Doctor's very, very good at it.",
      poster_path: '/sz4zF5z9zyFh8Z6g5IQPNq91cI7.jpg',
      media_type: 'tv',
      genre_ids: [
        10759,
        18,
        10765,
      ],
      popularity: 313.26,
      first_air_date: '2005-03-26',
      vote_average: 7.4,
      vote_count: 2447,
      origin_country: [
        'GB',
      ],
    },
  ],
  total_pages: 1000,
  total_results: 20000,
}
