// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Bg: typeof import('./src/components/layout/bg.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Footer: typeof import('./src/components/Footer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./src/components/layout/TheHeader.vue')['default']
  }
}
